---
framework: jest
preRun:
     command:
        - yarn install
        - yarn run clean
        - yarn run build
preMerge:
  pattern:
    - "./test/**/*.test.{tsx,ts}"
postMerge: 
  pattern: 
    - "./test/**/*.test.{tsx,ts}"
postRun:
     command:
        - yarn --version
version: 1.0
